### ISSUE TITLE
picomqtt in bridge mode?

### ISSUE THREAD

**Issue by Mit4el** [mlesniew/PicoMQTT#26]
is it possible to configure picomqtt in bridge mode? to send it to the mosquito. if possible, an example

**Comment by mlesniew** [comment]
Sure, that can be done with PicoMQTT.  

A very simple implementation could look more or less like this:
```
#include <PicoMQTT.h>

PicoMQTT::Client client("broker.hivemq.com");
PicoMQTT::Server server;

void setup() {
    server.subscribe("#", [](const char * topic, const char * message) {
        client.publish(topic, message);
     });

    client.subscribe("#", [](const char * topic, const char * message) {
        server.publish(topic, message);
    });
}

void loop() {
    client.loop();
    server.loop();
}
```

This should forward all messages published on the upstream broker to local clients and all messages published by local clients to the upstream broker.

**Comment by luotope** [comment]
Hi and thanks for the great software. 
I need exactly this solution where I'm having esp32 as a 'mid' broker in a separate system and which delivers messages also to my main broker and UI. The clients are esp8266 modules. 

My problem now is that these esp8266 modules need to know the ip of esp32 broker in order to connect to it. 
I would rather like to find out the ip via MDNS query, but all your examples show, however, that the server object address is given while creating the client object (PicoMQTT::Client client("broker.hivemq.com").

How can I set the broker ip in setup? PubSubClient for example is having a member setServer (mqtt.setServer(mqtt_serverIP, port)).

Thanks
Petri

**Comment by mlesniew** [comment]
You can create a matt client and simply provide an IP as string:

PicoMQTT::Client client("192.168.1.99");

mDNS addresses like "esp8266.local" should work too.

**Comment by mlesniew** [comment]
You can create a matt client and simply provide an IP as string:

PicoMQTT::Client client("192.168.1.99");

mDNS addresses like "esp8266.local" should work too.

**Comment by luotope** [comment]
I still don't understand how I make client global if I declare it in setup. I can find the ip only after MDNS query in setup.

So this works fine:
PicoMQTT::Client client("192.168.1.133");  
void setup() {
    Serial.begin(115200);
    .....

But this (simplified) do not, as client will not be global
void setup() {
    Serial.begin(115200);
    MDNS.queryService("esp32", "tcp");
    PicoMQTT::Client client(MDNS.hostname(0));  // host name or ip address  
    .....
   
Thanks for your help

**Comment by mlesniew** [comment]
PicoMQTT::Client must be global.

You can still set the broker address, port and credentials in the setup function by setting the corresponding public instance variables of the client object.

**Comment by luotope** [comment]
Ok. I found those variables and the solution is now working! Thanks.

In your documentation you state "_PicoMQTT::Server will not deliver published messages locally. This means that if you set up a PicoMQTT::Server and use subscribe, your callback will only be called when messages from clients are received_"

Can this be overriden somehow? The reason is that while this "mid" broker forwards messages from clients to main broker as explained above, the logic in this same ESP32 publishes also it's own gpio status. Now these published messages are received fine by the main broker, but **not** by a UI solution (NodeRed in raspberry Pi) which connects via mqtt to this ESP32 mid broker. The Pi only sees the messages published by the clients and by the main broker.

(To explain the solution a bit more, I can say that the esp8266 clients and ESP32 "mid broker" and the raspberry/Nodered UI are in my sailing boat as an independent solution. The broker, however delivers messages (position etc.) to the main broker which is at my home, another raspberry Pi UI & database). 

How could I get those broker-published messages visible when connecting to it? 

Thanks again.

**Comment by mlesniew** [comment]
Great it works for you now!
