### ISSUE TITLE
using PicoMQTT with websockets

### ISSUE THREAD

**Issue by mhaberler** [mlesniew/PicoMQTT#28]
Hi,

I appreciate your project - works much better for me than other Arduino MQTT broker projects

I would like to use your project with MQTT-over-websockets clients

I came up with a simple websockets-to-tcp proxy on a separe esp32:  https://github.com/mhaberler/arduino-websockets-tcp-proxy

this works fine with several MQTT-over-websockets clients, including paho-mqtt Python, paho-mqtt JS, and MQTT.js

however, as soon as I fold the websockets-to-tcp proxy into the same code as PicoMQTT, things get stuck during the MQTT connection handshake phase with the websockets clients-  it seems the broker disconnects: https://github.com/mhaberler/PicoMQTT-websockets

I’m asking for a look over my shoulder as I think this might be of wider interest and use -  I suspice there is something wrong with scheduling, yield or connect handling and I cant figure out why - I seem to violate some assumption which I am not aware of

thanks in advance!

Michael

**Comment by mhaberler** [comment]
I observed that a paho mqtt/Python client works fine, whereas paho mqtt/js and MQTT.js get stuck during connect

this is a paho mqtt/Python trace:
![Bildschirmfoto 2024-03-26 um 05 39 32](https://github.com/mlesniew/PicoMQTT/assets/901479/4fbfd53a-305b-48c6-9f72-6d08fbc701aa)

this is a paho mqtt/ws subscriber trace:

![Bildschirmfoto 2024-03-26 um 05 57 22](https://github.com/mlesniew/PicoMQTT/assets/901479/0e3450d9-4b97-4f49-9ca9-8820d6ca4333)

looks like a timeout during reassembly of the CONNECT websockets fragments

I'm using this dissector: https://github.com/nberthet/wireshark-mqtt-ws-plugin (seems to be struggling with fragmented websockets frames)

the PCAP files are at https://static.mah.priv.at/cors/paho-python.pcapng and https://static.mah.priv.at/cors/paho-js.pcapng

thanks in advance,

Michael

**Comment by mlesniew** [comment]
Hey Michael, thanks for trying to extend the library -- many people were asking about websocket support.

You're right that the library locks up at this point: https://github.com/mlesniew/PicoMQTT/blob/master/src/PicoMQTT/connection.cpp#L62-L78.

Your solution creates a web server socket to a simple tcp client socket proxy.  Everything that is received by the server is shoveled to the client socket.  Next you've configured the proxy to connect to PicoMQTT's broker port.   

This is an interesting hack, but as you've noticed it will not work correctly in some cases.  In the loop where the lockup happens, the PicoMQTT broker expects data to be received on its socket.  It will spin within that loop until a it gets all the required data or hits a timeout.  

Everything that already accumulated in the PicoMQTT's socket buffer will be read by the library fine.  However, if more data is expected, it will never be received.  This is because the `ProxyWebSocketsServer` might not have yet sent the data.  To make it forward data received on its websocket, its `loop()` would have to be called.

To fix this we would have to find a way to call `ProxyWebSocketsServer::loop()` from within this loop. 

Unfortunately this is not the only place where the library could lock up because of this.  So to really make this work in all cases, the `Connection` class (https://github.com/mlesniew/PicoMQTT/blob/640a3326fe6ca12ee673b38ea23e3a8c370d2790/src/PicoMQTT/connection.h#L25) would have to be extended.

I also see another problem.  Taking the approach you proposed will have significantly degraded performance and high resource use.  The solution uses three TCP sockets for each client instead of just one.  Each TCP connection is costly, especially on microcontroller boards, because of the need to maintain buffers and tracking what has been sent and what hasn't.

It would also be best to forward data received on the web socket directly into PicoMQTT instead of sending it through yey another socket.  

It would be ideal to introduce a class that inherits from Arduino's `Client` (https://github.com/esp8266/Arduino/blob/eda4e0855fa5ebcf1d7f621f35f25f6bab503335/cores/esp8266/Client.h#L26), just like `WiFiClient`, but internally encapsulates web socket communication.  PicoMQTT could then be extended to use that new class instead of the current one (perhaps leveraging c++ templates).  

This library seems like a good starting point: https://github.com/u0078867/Arduino-Websocket-Fast for doing that, but it's still a ton of work...

**Comment by mhaberler** [comment]
I have a working [interim solution ](https://github.com/mhaberler/PicoMQTT-websockets/blob/master/src/basic_server.cpp)

it was in fact quite simple:
- in the `Connection::wait_for_reply` loop, insert a `yield()`
- move the websockets proxy to a [separate RTOS thread](https://github.com/mhaberler/PicoMQTT-websockets/blob/master/src/basic_server.cpp#L17-L26)
- an [extra yield](https://github.com/mhaberler/PicoMQTT/blob/yield-in-wait-for-reply/src/PicoMQTT/connection.cpp#L170) which I'm not sure if it's actually required

while not very fast, this works fine with Paho MQTT/Python and JS with websockets transports, as well as MQTT.js

good enough for now until we have something more polished.

**Comment by mlesniew** [comment]
The library now supports websocket servers and clients as described in the [readme](https://github.com/mlesniew/PicoMQTT/?tab=readme-ov-file#websockets-support). 

I have now released the latest changes as version 1.0.0.  It should soon become installable via PlatformIO and the Arduino IDE.
