### ISSUE TITLE
Benchmark correctness

### ISSUE THREAD

**Issue by samipfjo** [mlesniew/PicoMQTT#31]
It is entirely possible that I'm reading the graphs wrong, but I am a little baffled why the ESP32 would perform so much worse than the ESP8266 given the former's faster processor. One would expect it to at minimum have the same performance. Is there some intrinsic bottleneck?

**Comment by mlesniew** [comment]
The library is much slower on the ESP32.  

From what I read online, this is not unusual.  People have reported that the ESP32 is slow on the network compared to the ESP8266.

It seems to be related to the fact that the ESP32 runs RTOS which adds overhead.  Additionally the network stack aims to be more complete and follow specifications more strictly.

On the ESP8266 there's a lightweight IP stack which trades speed and simplicity for safety and correctness.

Anyway, I haven't analysed it too much, because even with the reduced performance the library is sufficiently fast for most use cases.
