### ISSUE TITLE
publish + subscribe on same device

### ISSUE THREAD

**Issue by mhaberler** [mlesniew/PicoMQTT#32]
you write:

* `PicoMQTT::Server` will not deliver published messages locally.  This means that if you set up a `PicoMQTT::Server`
and use `subscribe`, your callback will only be called when messages from clients are received.  Messages published on
the same device will not trigger the callback.

is there a way to override this behavior - either on a publish or subscribe basis?

to explain the use case (whacky design alert):

- broker + LVGL UI on device
- LVGL UI objects are technically subscribed to MQTT topics
- some senor values come from off-device client like OMQ - works fine
- some sensors are on-device and published to the internal broker
- LVGL UI wont see them

I guess it could work with a local client, not the server publish API?

**Comment by mhaberler** [comment]
the first method (bypass the broker via `on_sensor_update`) works around the issue

however, compared to a subscription it has the disadvantage of send-always instead of send-on-payload-change

**Comment by mlesniew** [comment]
I've added some changes to support local subscribe -- they're currently on the [server_local_subscribe](https://github.com/mlesniew/PicoMQTT/tree/server_local_subscribe) branch.

Give it a try, probably all you'll have to change in your code is use `PicoMQTT::ServerLocalSubscribe` instead of `PicoMQTT::Server`, but have a look at [this section of the readme](https://github.com/mlesniew/PicoMQTT/tree/server_local_subscribe?tab=readme-ov-file#delivery-of-messages-published-on-the-broker) and the example.

**Comment by mhaberler** [comment]
really appreciated! 

will try it out and report.

**Comment by mlesniew** [comment]
The changes from the branch are now merged into master and included in release 1.1.0

**Comment by mhaberler** [comment]
did try it out - found no issues

**Comment by mlesniew** [comment]
Great, in that case, I'm closing the issue
